server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotao?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #spring boot默认是不注入这些属性的值，需要自己绑定
    #druid 数据源专有配置
    initial-size: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


    #配置统计拦截器 filters stat:监控统计 log4j:日志记录  wall:防御sql注入
    #如果允许报错 java.lang.ClassNotFoundException: org.apache.log4j.priority
    #则导入log4j的依赖即可.
    filters: stat,wall,log4j
    maxPoolParedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=500


#整合mybatis
mybatis:
  mapper-locations: com/example/fdl/mapper/*.xml
  type-aliases-package: com.example.fdl.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

